In [6]:
import numpy as np

a = np.array([[1, 2, 3],  [4, 5, 6]])
a.shape



(2, 3)

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
a



array([1, 2, 3, 4, 5, 6])

In [14]:
a[0]

np.int64(10)

In [18]:
a[0] = 10
a



array([10,  2,  3,  4,  5,  6])

In [19]:
a[:3]

array([10,  2,  3])

In [21]:
b = a[3:]
b


array([40,  5,  6])

In [22]:
b[0] = 40
a


array([10,  2,  3, 40,  5,  6])

In [23]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
a[1, 3]

np.int64(8)

In [26]:
a.ndim


2

In [27]:
a.shape


(3, 4)

In [32]:
len(a.shape) == a.ndim


True

In [33]:
a.size

12

In [34]:
import math
a.size == math.prod(a.shape)

True

In [35]:
a.dtype

dtype('int64')

In [36]:
np.zeros(2)


array([0., 0.])

In [37]:
np.ones(2)


array([1., 1.])

In [38]:
np.empty(2) 

array([1., 1.])

In [39]:
np.arange(4)


array([0, 1, 2, 3])

In [40]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [41]:
np.linspace(0, 10, num=5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [42]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [44]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim


3

In [50]:
array_example.size


24

In [51]:
array_example.shape


(3, 2, 4)

In [52]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [53]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [54]:
np.reshape(a, shape=(1, 6), order='C')


array([[0, 1, 2, 3, 4, 5]])

In [55]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [56]:
a2 = a[np.newaxis, :]
a2.shape


(1, 6)

In [57]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [58]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [59]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [60]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [61]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [62]:
data = np.array([1, 2, 3])

data[1]

np.int64(2)

In [63]:
data[0:2]

array([1, 2])

In [65]:
data[1:]

array([2, 3])

In [66]:
data[-2:]

array([2, 3])

In [67]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [68]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [69]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [70]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [71]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [73]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [74]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [75]:
print(a[b])

[1 2 3 4]


In [76]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [78]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [81]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [82]:
np.hstack((a1, a2))


array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [83]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [84]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [85]:
np.hsplit(x, (3, 4))


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [88]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [91]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [90]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
b2 = a.copy()
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [94]:
data - ones



array([0, 1])

In [95]:
data * data


array([1, 4])

In [96]:
data / data

array([1., 1.])

In [97]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [99]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)


array([3, 3])

In [100]:
b.sum(axis=1)


array([2, 4])

In [101]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [102]:
data = np.array([1, 2, 3])
data.max()


np.int64(3)

In [103]:

data.min()


np.int64(1)

In [104]:
data.sum()

np.int64(6)

In [107]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()


np.float64(4.8595784)

In [108]:
a.min()


np.float64(0.05093587)

In [109]:
a.min(axis=0)


array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [110]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
data[0, 1]


np.int64(2)

In [112]:

data[1:3]


array([[3, 4],
       [5, 6]])

In [113]:
data[0:2, 0]


array([1, 3])

In [114]:
data.max()


np.int64(6)

In [115]:
data.min()


np.int64(1)

In [116]:
data.sum()

np.int64(21)

In [117]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data


array([[1, 2],
       [5, 3],
       [4, 6]])

In [118]:
data.max(axis=0)


array([5, 6])

In [119]:
data.max(axis=1)


array([2, 5, 6])

In [122]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [123]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [124]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [125]:
np.ones(3)


array([1., 1., 1.])

In [126]:
np.zeros(3)

array([0., 0., 0.])

In [127]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.70427951, 0.41672405, 0.63287672])

In [128]:
np.ones((3, 2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [129]:
np.zeros((3, 2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [130]:
rng.random((3, 2)) 

array([[0.96184559, 0.74927753],
       [0.56906617, 0.98991992],
       [0.48132952, 0.63743563]])

In [131]:
rng.integers(5, size=(2, 4)) 

array([[1, 0, 4, 2],
       [0, 0, 2, 4]])

In [133]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)


[11 12 13 14 15 16 17 18 19 20]


In [134]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)


[ 0  2  3  4  5  6  7 12 13 14]


In [135]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)


[3 2 2 2 1 1 1 1 1 1]


In [137]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [138]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [139]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [140]:
print(indices)


[0 1 2]


In [141]:
print(occurrence_count)


[2 1 1]


In [142]:
data.reshape(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [143]:

data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [144]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [145]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [146]:
arr.T


array([[0, 3],
       [1, 4],
       [2, 5]])

In [149]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)


Reversed Array:  [8 7 6 5 4 3 2 1]


In [151]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [152]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [153]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [154]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [155]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [4]:
import numpy as np
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
